- name: deploy vlepo server
  hosts: web
  remote_user: root
  become: false
  gather_facts: no

  vars:
    vlepo_server_dir: /root/vlepo

  tasks:
    - name: stop existing server
      shell:
        cmd: "source /root/.zshrc && pm2 delete vlepo-server 2> /dev/null || true"
        executable: /usr/bin/zsh

    - name: remove existing target dir
      file:
        path: "{{ vlepo_server_dir }}"
        state: absent

    - name: ensure target dir exists
      file:
        path: "{{ vlepo_server_dir }}"
        state: directory
        mode: "0755"

    - name: ensure target server dir exists
      file:
        path: "{{ vlepo_server_dir }}/server"
        state: directory
        mode: "0755"

    - name: copy built vlepo-server archive to target server dir
      copy:
        src: ../artifact/vlepo-server.zip
        dest: "{{ vlepo_server_dir }}/vlepo-server.zip"
        owner: root
        group: root
        mode: "0644"

    - name: unarchive vlepo-server
      unarchive:
        remote_src: yes
        src: "{{ vlepo_server_dir }}/vlepo-server.zip"
        dest: "{{ vlepo_server_dir }}/server/"

    - name: link env file
      file:
        src: "/root/.env"
        dest: "{{ vlepo_server_dir }}/server/build/.env"
        state: link

    - name: install dependencies
      shell:
        cmd: source /root/.zshrc && yarn
        executable: /usr/bin/zsh
        chdir: "{{ vlepo_server_dir }}/server/build/"
      async: 1000
      poll: 0
      register: yarn_install

    - name: "waiting for yarn install"
      async_status:
        jid: "{{ yarn_install.ansible_job_id }}"
      register: yarn_install_result
      until: yarn_install_result.finished
      retries: 60
      delay: 5

    - name: database client generation
      shell:
        cmd: source /root/.zshrc && yarn db:migrate
        executable: /usr/bin/zsh
        chdir: "{{ vlepo_server_dir }}/server/build/"
      async: 1000
      poll: 0
      register: db_client_generation

    - name: "waiting for database client generation"
      async_status:
        jid: "{{ db_client_generation.ansible_job_id }}"
      register: db_client_generation_result
      until: db_client_generation_result.finished
      retries: 60
      delay: 5

    - name: database migration
      shell:
        cmd: source /root/.zshrc && yarn db:migrate
        executable: /usr/bin/zsh
        chdir: "{{ vlepo_server_dir }}/server/build/"
      async: 1000
      poll: 0
      register: db_migrate

    - name: "waiting for database migration"
      async_status:
        jid: "{{ db_client_generation.ansible_job_id }}"
      register: db_migrate_result
      until: db_migrate_result.finished
      retries: 60
      delay: 5

    - name: run server
      shell:
        cmd: "source /root/.zshrc && yarn start"
        executable: /usr/bin/zsh
        chdir: "{{ vlepo_server_dir }}/server/build/"
