name: deploy-prod

on:
  push:
    branches: [main]

# needed for terraform
env:
  ENVIRONMENT: staging

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      DEPLOY_INFRA: ${{ steps.determine_infra.outputs.DEPLOY_INFRA }}
      DEPLOY_API: ${{ steps.determine_api.outputs.DEPLOY_API }}
      DEPLOY_WEB: ${{ steps.determine_web.outputs.DEPLOY_WEB }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - id: determine_infra
        name: determine if infra needs to be deployed
        run: |
          if ! git diff HEAD^ HEAD --quiet ./devops/infrastructure; then
              echo "::set-output name=DEPLOY_INFRA::true"
          fi

      - id: determine_api
        name: determine if api needs to be deployed
        run: |
          if ! git diff HEAD^ HEAD --quiet ./apps/api; then
              echo "::set-output name=DEPLOY_API::true"
          fi
          if ! git diff HEAD^ HEAD --quiet ./packages/helpers; then
              echo "::set-output name=DEPLOY_API::true"
          fi
          if ! git diff HEAD^ HEAD --quiet ./devops/docker/api.dockerfile; then
              echo "::set-output name=DEPLOY_API::true"
          fi

      - id: determine_web
        name: determine if web needs to be deployed
        run: |
          if ! git diff HEAD^ HEAD --quiet ./apps/web; then
              echo "::set-output name=DEPLOY_WEB::true"
          fi
          if ! git diff HEAD^ HEAD --quiet ./packages/ui; then
              echo "::set-output name=DEPLOY_WEB::true"
          fi
          if ! git diff HEAD^ HEAD --quiet ./devops/docker/web.dockerfile; then
              echo "::set-output name=DEPLOY_WEB::true"
          fi

  deploy-infra:
    runs-on: ubuntu-latest
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.DEPLOY_INFRA == 'true' }}

    environment:
      name: production

    steps:
      - uses: actions/checkout@v3

      - name: azure cli login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: use terraform

        uses: hashicorp/setup-terraform@v2

      - name: terraform plan
        run: yarn plan
        env:
          TF_VAR_DB_TUNNEL_IP: ${{ secrets.TF_VAR_DB_TUNNEL_IP }}
          TF_VAR_ENVIRONMENT: ${{ secrets.TF_VAR_ENVIRONMENT }}
          TF_VAR_USER_PRINCIPAL_ID: ${{ secrets.TF_VAR_USER_PRINCIPAL_ID }}

      - name: terraform apply
        run: yarn apply
        env:
          TF_VAR_DB_TUNNEL_IP: ${{ secrets.TF_VAR_DB_TUNNEL_IP }}
          TF_VAR_ENVIRONMENT: ${{ secrets.TF_VAR_ENVIRONMENT }}
          TF_VAR_USER_PRINCIPAL_ID: ${{ secrets.TF_VAR_USER_PRINCIPAL_ID }}

  deploy-api:
    runs-on: ubuntu-latest
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.DEPLOY_API == 'true' }}

    environment:
      name: production

    steps:
      - uses: actions/checkout@v3

      - name: build api container and push to acr
        run: devops/docker/deploy-api.sh
        env:
          SKIP_READ_SECRETS: true
          SKIP_RESTART: true

      - name: azure cli login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: restart api service after build
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp restart --name vlepo-api --resource-group vlepo-resources-${ENVIRONMENT}

  deploy-web:
    runs-on: ubuntu-latest
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.DEPLOY_WEB == 'true' }}

    environment:
      name: production

    steps:
      - uses: actions/checkout@v3

      - name: build web container and push to acr
        run: devops/docker/deploy-web.sh
        env:
          SKIP_READ_SECRETS: true
          SKIP_RESTART: true
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
          NEXT_PUBLIC_ALGOLIA_API_KEY: ${{ secrets.NEXT_PUBLIC_ALGOLIA_API_KEY }}
          NEXT_PUBLIC_ALGOLIA_APP_ID: ${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID }}
          NEXT_PUBLIC_ALGOLIA_INDEX_NAME: ${{ secrets.NEXT_PUBLIC_ALGOLIA_INDEX_NAME }}
          NEXT_PUBLIC_API_ENDPOINT: ${{ secrets.NEXT_PUBLIC_API_ENDPOINT }}
          NEXT_PUBLIC_CDN_URL: ${{ secrets.NEXT_PUBLIC_CDN_URL }}
          NEXT_PUBLIC_DEFAULT_BLOG_ID: ${{ secrets.NEXT_PUBLIC_DEFAULT_BLOG_ID }}
          NEXT_PUBLIC_DEFAULT_BLOG_NAME: ${{ secrets.NEXT_PUBLIC_DEFAULT_BLOG_NAME }}
          NEXT_PUBLIC_DEFAULT_BLOG_SLOGAN: ${{ secrets.NEXT_PUBLIC_DEFAULT_BLOG_SLOGAN }}
          NEXT_PUBLIC_DEFAULT_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_DEFAULT_CLIENT_ID }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
          NEXT_PUBLIC_SUPPORTED_OAUTH_PROVIDERS: ${{ secrets.NEXT_PUBLIC_SUPPORTED_OAUTH_PROVIDERS }}

      - name: azure cli login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: restart web service after build
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp restart --name vlepo-web --resource-group vlepo-resources-${ENVIRONMENT}
